version: '3'
services:
  redis:
    image: 'redis:4-alpine'
    ports:
      - '6379:6379'
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
  rabbitmq:
    image: 'bitnami/rabbitmq:latest'
    environment:
      - RABBITMQ_USERNAME=root
      - RABBITMQ_PASSWORD=root